// Copyright 2020-2024 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by github.com/bufbuild/protocompile/internal/enum. DO NOT EDIT.

package token

import (
	"fmt"
)

// String implements [fmt.Stringer].
func (v Kind) String() string {
	if int(v) < 0 || int(v) > len(_KindStrings) {
		return fmt.Sprintf("Kind(%v)", int(v))
	}
	return _KindStrings[int(v)]
}

var _KindStrings = [...]string {
	Unrecognized: "Unrecognized",
	Space: "Space",
	Comment: "Comment",
	Ident: "Ident",
	String: "String",
	Number: "Number",
	Punct: "Punct",
}

// GoString implements [fmt.GoStringer].
func (v Kind) GoString() string {
	if int(v) < 0 || int(v) > len(_KindStrings) {
		return fmt.Sprintf("token.Kind(%v)", int(v))
	}
	return _KindStrings[int(v)]
}

var _KindGoStrings = [...]string {
	Unrecognized: "token.Unrecognized",
	Space: "token.Space",
	Comment: "token.Comment",
	Ident: "token.Ident",
	String: "token.String",
	Number: "token.Number",
	Punct: "token.Punct",
}

