edition = "2026";

package buf.test;

import "google/protobuf/descriptor.proto";

option cc_enable_arenas = true;

extend google.protobuf.MessageOptions {
    bool old = 50000 [feature_support = {
        edition_introduced: EDITION_2023
        edition_deprecated: EDITION_2024
        deprecation_warning: "Use `new` instead."
        edition_removed: EDITION_2026
        removal_error: "Use `new` instead."
    }];
    Nested nested = 50001;
}

export message Nested {
    bool deprecated = 1 [feature_support = {
        edition_introduced: EDITION_2023
        edition_deprecated: EDITION_2026
        deprecation_warning: "Don't use this."
    }];
}

export message Foo {
    option (old) = true;
    option (nested).deprecated = true;
}
