// Copyright 2020-2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by github.com/bufbuild/protocompile/internal/tags/gen. DO NOT EDIT.

package tags

const (
	// Field number for google.protobuf.FileDescriptorSet.file.
	FileDescriptorSet_File = 1

	// Field number for google.protobuf.FileDescriptorProto.name.
	File_Name = 1

	// Field number for google.protobuf.FileDescriptorProto.package.
	File_Package = 2

	// Field number for google.protobuf.FileDescriptorProto.dependency.
	File_Dependency = 3

	// Field number for google.protobuf.FileDescriptorProto.public_dependency.
	File_PublicDependency = 10

	// Field number for google.protobuf.FileDescriptorProto.weak_dependency.
	File_WeakDependency = 11

	// Field number for google.protobuf.FileDescriptorProto.option_dependency.
	File_OptionDependency = 15

	// Field number for google.protobuf.FileDescriptorProto.message_type.
	File_MessageType = 4

	// Field number for google.protobuf.FileDescriptorProto.enum_type.
	File_EnumType = 5

	// Field number for google.protobuf.FileDescriptorProto.service.
	File_Service = 6

	// Field number for google.protobuf.FileDescriptorProto.extension.
	File_Extension = 7

	// Field number for google.protobuf.FileDescriptorProto.options.
	File_Options = 8

	// Field number for google.protobuf.FileDescriptorProto.source_code_info.
	File_SourceCodeInfo = 9

	// Field number for google.protobuf.FileDescriptorProto.syntax.
	File_Syntax = 12

	// Field number for google.protobuf.FileDescriptorProto.edition.
	File_Edition = 14

	// Field number for google.protobuf.DescriptorProto.name.
	Message_Name = 1

	// Field number for google.protobuf.DescriptorProto.field.
	Message_Field = 2

	// Field number for google.protobuf.DescriptorProto.extension.
	Message_Extension = 6

	// Field number for google.protobuf.DescriptorProto.nested_type.
	Message_NestedType = 3

	// Field number for google.protobuf.DescriptorProto.enum_type.
	Message_EnumType = 4

	// Field number for google.protobuf.DescriptorProto.extension_range.
	Message_ExtensionRange = 5

	// Field number for google.protobuf.DescriptorProto.oneof_decl.
	Message_OneofDecl = 8

	// Field number for google.protobuf.DescriptorProto.options.
	Message_Options = 7

	// Field number for google.protobuf.DescriptorProto.reserved_range.
	Message_ReservedRange = 9

	// Field number for google.protobuf.DescriptorProto.reserved_name.
	Message_ReservedName = 10

	// Field number for google.protobuf.DescriptorProto.visibility.
	Message_Visibility = 11

	// Field number for google.protobuf.DescriptorProto.ExtensionRange.start.
	Message_ExtensionRange_Start = 1

	// Field number for google.protobuf.DescriptorProto.ExtensionRange.end.
	Message_ExtensionRange_End = 2

	// Field number for google.protobuf.DescriptorProto.ExtensionRange.options.
	Message_ExtensionRange_Options = 3

	// Field number for google.protobuf.DescriptorProto.ReservedRange.start.
	Message_ReservedRange_Start = 1

	// Field number for google.protobuf.DescriptorProto.ReservedRange.end.
	Message_ReservedRange_End = 2

	// Field number for google.protobuf.ExtensionRangeOptions.uninterpreted_option.
	ExtensionRangeOptions_UninterpretedOption = 999

	// Field number for google.protobuf.ExtensionRangeOptions.declaration.
	ExtensionRangeOptions_Declaration = 2

	// Field number for google.protobuf.ExtensionRangeOptions.features.
	ExtensionRangeOptions_Features = 50

	// Field number for google.protobuf.ExtensionRangeOptions.verification.
	ExtensionRangeOptions_Verification = 3

	// Field number for google.protobuf.ExtensionRangeOptions.Declaration.number.
	ExtensionRangeOptions_Declaration_Number = 1

	// Field number for google.protobuf.ExtensionRangeOptions.Declaration.full_name.
	ExtensionRangeOptions_Declaration_FullName = 2

	// Field number for google.protobuf.ExtensionRangeOptions.Declaration.type.
	ExtensionRangeOptions_Declaration_Type = 3

	// Field number for google.protobuf.ExtensionRangeOptions.Declaration.reserved.
	ExtensionRangeOptions_Declaration_Reserved = 5

	// Field number for google.protobuf.ExtensionRangeOptions.Declaration.repeated.
	ExtensionRangeOptions_Declaration_Repeated = 6

	// Field number for google.protobuf.FieldDescriptorProto.name.
	Field_Name = 1

	// Field number for google.protobuf.FieldDescriptorProto.number.
	Field_Number = 3

	// Field number for google.protobuf.FieldDescriptorProto.label.
	Field_Label = 4

	// Field number for google.protobuf.FieldDescriptorProto.type.
	Field_Type = 5

	// Field number for google.protobuf.FieldDescriptorProto.type_name.
	Field_TypeName = 6

	// Field number for google.protobuf.FieldDescriptorProto.extendee.
	Field_Extendee = 2

	// Field number for google.protobuf.FieldDescriptorProto.default_value.
	Field_DefaultValue = 7

	// Field number for google.protobuf.FieldDescriptorProto.oneof_index.
	Field_OneofIndex = 9

	// Field number for google.protobuf.FieldDescriptorProto.json_name.
	Field_JsonName = 10

	// Field number for google.protobuf.FieldDescriptorProto.options.
	Field_Options = 8

	// Field number for google.protobuf.FieldDescriptorProto.proto3_optional.
	Field_Proto3Optional = 17

	// Field number for google.protobuf.OneofDescriptorProto.name.
	Oneof_Name = 1

	// Field number for google.protobuf.OneofDescriptorProto.options.
	Oneof_Options = 2

	// Field number for google.protobuf.EnumDescriptorProto.name.
	Enum_Name = 1

	// Field number for google.protobuf.EnumDescriptorProto.value.
	Enum_Value = 2

	// Field number for google.protobuf.EnumDescriptorProto.options.
	Enum_Options = 3

	// Field number for google.protobuf.EnumDescriptorProto.reserved_range.
	Enum_ReservedRange = 4

	// Field number for google.protobuf.EnumDescriptorProto.reserved_name.
	Enum_ReservedName = 5

	// Field number for google.protobuf.EnumDescriptorProto.visibility.
	Enum_Visibility = 6

	// Field number for google.protobuf.EnumDescriptorProto.EnumReservedRange.start.
	Enum_ReservedRange_Start = 1

	// Field number for google.protobuf.EnumDescriptorProto.EnumReservedRange.end.
	Enum_ReservedRange_End = 2

	// Field number for google.protobuf.EnumValueDescriptorProto.name.
	EnumValue_Name = 1

	// Field number for google.protobuf.EnumValueDescriptorProto.number.
	EnumValue_Number = 2

	// Field number for google.protobuf.EnumValueDescriptorProto.options.
	EnumValue_Options = 3

	// Field number for google.protobuf.ServiceDescriptorProto.name.
	Service_Name = 1

	// Field number for google.protobuf.ServiceDescriptorProto.method.
	Service_Method = 2

	// Field number for google.protobuf.ServiceDescriptorProto.options.
	Service_Options = 3

	// Field number for google.protobuf.MethodDescriptorProto.name.
	Method_Name = 1

	// Field number for google.protobuf.MethodDescriptorProto.input_type.
	Method_InputType = 2

	// Field number for google.protobuf.MethodDescriptorProto.output_type.
	Method_OutputType = 3

	// Field number for google.protobuf.MethodDescriptorProto.options.
	Method_Options = 4

	// Field number for google.protobuf.MethodDescriptorProto.client_streaming.
	Method_ClientStreaming = 5

	// Field number for google.protobuf.MethodDescriptorProto.server_streaming.
	Method_ServerStreaming = 6

	// Field number for google.protobuf.FileOptions.java_package.
	FileOptions_JavaPackage = 1

	// Field number for google.protobuf.FileOptions.java_outer_classname.
	FileOptions_JavaOuterClassname = 8

	// Field number for google.protobuf.FileOptions.java_multiple_files.
	FileOptions_JavaMultipleFiles = 10

	// Field number for google.protobuf.FileOptions.java_generate_equals_and_hash.
	FileOptions_JavaGenerateEqualsAndHash = 20

	// Field number for google.protobuf.FileOptions.java_string_check_utf8.
	FileOptions_JavaStringCheckUtf8 = 27

	// Field number for google.protobuf.FileOptions.optimize_for.
	FileOptions_OptimizeFor = 9

	// Field number for google.protobuf.FileOptions.go_package.
	FileOptions_GoPackage = 11

	// Field number for google.protobuf.FileOptions.cc_generic_services.
	FileOptions_CcGenericServices = 16

	// Field number for google.protobuf.FileOptions.java_generic_services.
	FileOptions_JavaGenericServices = 17

	// Field number for google.protobuf.FileOptions.py_generic_services.
	FileOptions_PyGenericServices = 18

	// Field number for google.protobuf.FileOptions.deprecated.
	FileOptions_Deprecated = 23

	// Field number for google.protobuf.FileOptions.cc_enable_arenas.
	FileOptions_CcEnableArenas = 31

	// Field number for google.protobuf.FileOptions.objc_class_prefix.
	FileOptions_ObjcClassPrefix = 36

	// Field number for google.protobuf.FileOptions.csharp_namespace.
	FileOptions_CsharpNamespace = 37

	// Field number for google.protobuf.FileOptions.swift_prefix.
	FileOptions_SwiftPrefix = 39

	// Field number for google.protobuf.FileOptions.php_class_prefix.
	FileOptions_PhpClassPrefix = 40

	// Field number for google.protobuf.FileOptions.php_namespace.
	FileOptions_PhpNamespace = 41

	// Field number for google.protobuf.FileOptions.php_metadata_namespace.
	FileOptions_PhpMetadataNamespace = 44

	// Field number for google.protobuf.FileOptions.ruby_package.
	FileOptions_RubyPackage = 45

	// Field number for google.protobuf.FileOptions.features.
	FileOptions_Features = 50

	// Field number for google.protobuf.FileOptions.uninterpreted_option.
	FileOptions_UninterpretedOption = 999

	// Field number for google.protobuf.MessageOptions.message_set_wire_format.
	MessageOptions_MessageSetWireFormat = 1

	// Field number for google.protobuf.MessageOptions.no_standard_descriptor_accessor.
	MessageOptions_NoStandardDescriptorAccessor = 2

	// Field number for google.protobuf.MessageOptions.deprecated.
	MessageOptions_Deprecated = 3

	// Field number for google.protobuf.MessageOptions.map_entry.
	MessageOptions_MapEntry = 7

	// Field number for google.protobuf.MessageOptions.deprecated_legacy_json_field_conflicts.
	MessageOptions_DeprecatedLegacyJsonFieldConflicts = 11

	// Field number for google.protobuf.MessageOptions.features.
	MessageOptions_Features = 12

	// Field number for google.protobuf.MessageOptions.uninterpreted_option.
	MessageOptions_UninterpretedOption = 999

	// Field number for google.protobuf.FieldOptions.ctype.
	FieldOptions_Ctype = 1

	// Field number for google.protobuf.FieldOptions.packed.
	FieldOptions_Packed = 2

	// Field number for google.protobuf.FieldOptions.jstype.
	FieldOptions_Jstype = 6

	// Field number for google.protobuf.FieldOptions.lazy.
	FieldOptions_Lazy = 5

	// Field number for google.protobuf.FieldOptions.unverified_lazy.
	FieldOptions_UnverifiedLazy = 15

	// Field number for google.protobuf.FieldOptions.deprecated.
	FieldOptions_Deprecated = 3

	// Field number for google.protobuf.FieldOptions.weak.
	FieldOptions_Weak = 10

	// Field number for google.protobuf.FieldOptions.debug_redact.
	FieldOptions_DebugRedact = 16

	// Field number for google.protobuf.FieldOptions.retention.
	FieldOptions_Retention = 17

	// Field number for google.protobuf.FieldOptions.targets.
	FieldOptions_Targets = 19

	// Field number for google.protobuf.FieldOptions.edition_defaults.
	FieldOptions_EditionDefaults = 20

	// Field number for google.protobuf.FieldOptions.features.
	FieldOptions_Features = 21

	// Field number for google.protobuf.FieldOptions.feature_support.
	FieldOptions_FeatureSupport = 22

	// Field number for google.protobuf.FieldOptions.uninterpreted_option.
	FieldOptions_UninterpretedOption = 999

	// Field number for google.protobuf.FieldOptions.EditionDefault.edition.
	FieldOptions_EditionDefault_Edition = 3

	// Field number for google.protobuf.FieldOptions.EditionDefault.value.
	FieldOptions_EditionDefault_Value = 2

	// Field number for google.protobuf.FieldOptions.FeatureSupport.edition_introduced.
	FieldOptions_FeatureSupport_EditionIntroduced = 1

	// Field number for google.protobuf.FieldOptions.FeatureSupport.edition_deprecated.
	FieldOptions_FeatureSupport_EditionDeprecated = 2

	// Field number for google.protobuf.FieldOptions.FeatureSupport.deprecation_warning.
	FieldOptions_FeatureSupport_DeprecationWarning = 3

	// Field number for google.protobuf.FieldOptions.FeatureSupport.edition_removed.
	FieldOptions_FeatureSupport_EditionRemoved = 4

	// Field number for google.protobuf.OneofOptions.features.
	OneofOptions_Features = 1

	// Field number for google.protobuf.OneofOptions.uninterpreted_option.
	OneofOptions_UninterpretedOption = 999

	// Field number for google.protobuf.EnumOptions.allow_alias.
	EnumOptions_AllowAlias = 2

	// Field number for google.protobuf.EnumOptions.deprecated.
	EnumOptions_Deprecated = 3

	// Field number for google.protobuf.EnumOptions.deprecated_legacy_json_field_conflicts.
	EnumOptions_DeprecatedLegacyJsonFieldConflicts = 6

	// Field number for google.protobuf.EnumOptions.features.
	EnumOptions_Features = 7

	// Field number for google.protobuf.EnumOptions.uninterpreted_option.
	EnumOptions_UninterpretedOption = 999

	// Field number for google.protobuf.EnumValueOptions.deprecated.
	EnumValueOptions_Deprecated = 1

	// Field number for google.protobuf.EnumValueOptions.features.
	EnumValueOptions_Features = 2

	// Field number for google.protobuf.EnumValueOptions.debug_redact.
	EnumValueOptions_DebugRedact = 3

	// Field number for google.protobuf.EnumValueOptions.feature_support.
	EnumValueOptions_FeatureSupport = 4

	// Field number for google.protobuf.EnumValueOptions.uninterpreted_option.
	EnumValueOptions_UninterpretedOption = 999

	// Field number for google.protobuf.ServiceOptions.features.
	ServiceOptions_Features = 34

	// Field number for google.protobuf.ServiceOptions.deprecated.
	ServiceOptions_Deprecated = 33

	// Field number for google.protobuf.ServiceOptions.uninterpreted_option.
	ServiceOptions_UninterpretedOption = 999

	// Field number for google.protobuf.MethodOptions.deprecated.
	MethodOptions_Deprecated = 33

	// Field number for google.protobuf.MethodOptions.idempotency_level.
	MethodOptions_IdempotencyLevel = 34

	// Field number for google.protobuf.MethodOptions.features.
	MethodOptions_Features = 35

	// Field number for google.protobuf.MethodOptions.uninterpreted_option.
	MethodOptions_UninterpretedOption = 999

	// Field number for google.protobuf.UninterpretedOption.name.
	UninterpretedOption_Name = 2

	// Field number for google.protobuf.UninterpretedOption.identifier_value.
	UninterpretedOption_IdentifierValue = 3

	// Field number for google.protobuf.UninterpretedOption.positive_int_value.
	UninterpretedOption_PositiveIntValue = 4

	// Field number for google.protobuf.UninterpretedOption.negative_int_value.
	UninterpretedOption_NegativeIntValue = 5

	// Field number for google.protobuf.UninterpretedOption.double_value.
	UninterpretedOption_DoubleValue = 6

	// Field number for google.protobuf.UninterpretedOption.string_value.
	UninterpretedOption_StringValue = 7

	// Field number for google.protobuf.UninterpretedOption.aggregate_value.
	UninterpretedOption_AggregateValue = 8

	// Field number for google.protobuf.UninterpretedOption.NamePart.name_part.
	UninterpretedOption_NamePart_NamePart = 1

	// Field number for google.protobuf.UninterpretedOption.NamePart.is_extension.
	UninterpretedOption_NamePart_IsExtension = 2

	// Field number for google.protobuf.FeatureSet.field_presence.
	FeatureSet_FieldPresence = 1

	// Field number for google.protobuf.FeatureSet.enum_type.
	FeatureSet_EnumType = 2

	// Field number for google.protobuf.FeatureSet.repeated_field_encoding.
	FeatureSet_RepeatedFieldEncoding = 3

	// Field number for google.protobuf.FeatureSet.utf8_validation.
	FeatureSet_Utf8Validation = 4

	// Field number for google.protobuf.FeatureSet.message_encoding.
	FeatureSet_MessageEncoding = 5

	// Field number for google.protobuf.FeatureSet.json_format.
	FeatureSet_JsonFormat = 6

	// Field number for google.protobuf.FeatureSet.enforce_naming_style.
	FeatureSet_EnforceNamingStyle = 7

	// Field number for google.protobuf.FeatureSet.default_symbol_visibility.
	FeatureSet_DefaultSymbolVisibility = 8

	// Field number for google.protobuf.FeatureSetDefaults.defaults.
	FeatureSetDefaults_Defaults = 1

	// Field number for google.protobuf.FeatureSetDefaults.minimum_edition.
	FeatureSetDefaults_MinimumEdition = 4

	// Field number for google.protobuf.FeatureSetDefaults.maximum_edition.
	FeatureSetDefaults_MaximumEdition = 5

	// Field number for google.protobuf.FeatureSetDefaults.FeatureSetEditionDefault.edition.
	FeatureSetDefaults_FeatureSetEditionDefault_Edition = 3

	// Field number for google.protobuf.FeatureSetDefaults.FeatureSetEditionDefault.overridable_features.
	FeatureSetDefaults_FeatureSetEditionDefault_OverridableFeatures = 4

	// Field number for google.protobuf.FeatureSetDefaults.FeatureSetEditionDefault.fixed_features.
	FeatureSetDefaults_FeatureSetEditionDefault_FixedFeatures = 5

	// Field number for google.protobuf.SourceCodeInfo.location.
	SourceCodeInfo_Location = 1

	// Field number for google.protobuf.SourceCodeInfo.Location.path.
	SourceCodeInfo_Location_Path = 1

	// Field number for google.protobuf.SourceCodeInfo.Location.span.
	SourceCodeInfo_Location_Span = 2

	// Field number for google.protobuf.SourceCodeInfo.Location.leading_comments.
	SourceCodeInfo_Location_LeadingComments = 3

	// Field number for google.protobuf.SourceCodeInfo.Location.trailing_comments.
	SourceCodeInfo_Location_TrailingComments = 4

	// Field number for google.protobuf.SourceCodeInfo.Location.leading_detached_comments.
	SourceCodeInfo_Location_LeadingDetachedComments = 6

	// Field number for google.protobuf.GeneratedCodeInfo.annotation.
	GeneratedCodeInfo_Annotation = 1

	// Field number for google.protobuf.GeneratedCodeInfo.Annotation.path.
	GeneratedCodeInfo_Annotation_Path = 1

	// Field number for google.protobuf.GeneratedCodeInfo.Annotation.source_file.
	GeneratedCodeInfo_Annotation_SourceFile = 2

	// Field number for google.protobuf.GeneratedCodeInfo.Annotation.begin.
	GeneratedCodeInfo_Annotation_Begin = 3

	// Field number for google.protobuf.GeneratedCodeInfo.Annotation.end.
	GeneratedCodeInfo_Annotation_End = 4

	// Field number for google.protobuf.GeneratedCodeInfo.Annotation.semantic.
	GeneratedCodeInfo_Annotation_Semantic = 5

	// Field number for google.protobuf.Any.type_url.
	Any_TypeUrl = 1

	// Field number for google.protobuf.Any.value.
	Any_Value = 2
)

const (
	// Enum value for google.protobuf.EDITION_UNKNOWN.
	Edition_Unknown = 0

	// Enum value for google.protobuf.EDITION_LEGACY.
	Edition_Legacy = 900

	// Enum value for google.protobuf.EDITION_PROTO2.
	Edition_Proto2 = 998

	// Enum value for google.protobuf.EDITION_PROTO3.
	Edition_Proto3 = 999

	// Enum value for google.protobuf.EDITION_2023.
	Edition_2023 = 1000

	// Enum value for google.protobuf.EDITION_2024.
	Edition_2024 = 1001

	// Enum value for google.protobuf.EDITION_UNSTABLE.
	Edition_Unstable = 9999

	// Enum value for google.protobuf.EDITION_1_TEST_ONLY.
	Edition_1TestOnly = 1

	// Enum value for google.protobuf.EDITION_2_TEST_ONLY.
	Edition_2TestOnly = 2

	// Enum value for google.protobuf.EDITION_99997_TEST_ONLY.
	Edition_99997TestOnly = 99997

	// Enum value for google.protobuf.EDITION_99998_TEST_ONLY.
	Edition_99998TestOnly = 99998

	// Enum value for google.protobuf.EDITION_99999_TEST_ONLY.
	Edition_99999TestOnly = 99999

	// Enum value for google.protobuf.EDITION_MAX.
	Edition_Max = 2147483647

	// Enum value for google.protobuf.VISIBILITY_UNSET.
	SymbolVisibility_Unset = 0

	// Enum value for google.protobuf.VISIBILITY_LOCAL.
	SymbolVisibility_Local = 1

	// Enum value for google.protobuf.VISIBILITY_EXPORT.
	SymbolVisibility_Export = 2

	// Enum value for google.protobuf.ExtensionRangeOptions.DECLARATION.
	ExtensionRangeOptions_VerificationState_Declaration = 0

	// Enum value for google.protobuf.ExtensionRangeOptions.UNVERIFIED.
	ExtensionRangeOptions_VerificationState_Unverified = 1

	// Enum value for google.protobuf.FieldDescriptorProto.TYPE_DOUBLE.
	Field_Type_Double = 1

	// Enum value for google.protobuf.FieldDescriptorProto.TYPE_FLOAT.
	Field_Type_Float = 2

	// Enum value for google.protobuf.FieldDescriptorProto.TYPE_INT64.
	Field_Type_Int64 = 3

	// Enum value for google.protobuf.FieldDescriptorProto.TYPE_UINT64.
	Field_Type_Uint64 = 4

	// Enum value for google.protobuf.FieldDescriptorProto.TYPE_INT32.
	Field_Type_Int32 = 5

	// Enum value for google.protobuf.FieldDescriptorProto.TYPE_FIXED64.
	Field_Type_Fixed64 = 6

	// Enum value for google.protobuf.FieldDescriptorProto.TYPE_FIXED32.
	Field_Type_Fixed32 = 7

	// Enum value for google.protobuf.FieldDescriptorProto.TYPE_BOOL.
	Field_Type_Bool = 8

	// Enum value for google.protobuf.FieldDescriptorProto.TYPE_STRING.
	Field_Type_String = 9

	// Enum value for google.protobuf.FieldDescriptorProto.TYPE_GROUP.
	Field_Type_Group = 10

	// Enum value for google.protobuf.FieldDescriptorProto.TYPE_MESSAGE.
	Field_Type_Message = 11

	// Enum value for google.protobuf.FieldDescriptorProto.TYPE_BYTES.
	Field_Type_Bytes = 12

	// Enum value for google.protobuf.FieldDescriptorProto.TYPE_UINT32.
	Field_Type_Uint32 = 13

	// Enum value for google.protobuf.FieldDescriptorProto.TYPE_ENUM.
	Field_Type_Enum = 14

	// Enum value for google.protobuf.FieldDescriptorProto.TYPE_SFIXED32.
	Field_Type_Sfixed32 = 15

	// Enum value for google.protobuf.FieldDescriptorProto.TYPE_SFIXED64.
	Field_Type_Sfixed64 = 16

	// Enum value for google.protobuf.FieldDescriptorProto.TYPE_SINT32.
	Field_Type_Sint32 = 17

	// Enum value for google.protobuf.FieldDescriptorProto.TYPE_SINT64.
	Field_Type_Sint64 = 18

	// Enum value for google.protobuf.FieldDescriptorProto.LABEL_OPTIONAL.
	Field_Label_Optional = 1

	// Enum value for google.protobuf.FieldDescriptorProto.LABEL_REPEATED.
	Field_Label_Repeated = 3

	// Enum value for google.protobuf.FieldDescriptorProto.LABEL_REQUIRED.
	Field_Label_Required = 2

	// Enum value for google.protobuf.FileOptions.SPEED.
	FileOptions_OptimizeMode_Speed = 1

	// Enum value for google.protobuf.FileOptions.CODE_SIZE.
	FileOptions_OptimizeMode_CodeSize = 2

	// Enum value for google.protobuf.FileOptions.LITE_RUNTIME.
	FileOptions_OptimizeMode_LiteRuntime = 3

	// Enum value for google.protobuf.FieldOptions.STRING.
	FieldOptions_CType_String = 0

	// Enum value for google.protobuf.FieldOptions.CORD.
	FieldOptions_CType_Cord = 1

	// Enum value for google.protobuf.FieldOptions.STRING_PIECE.
	FieldOptions_CType_StringPiece = 2

	// Enum value for google.protobuf.FieldOptions.JS_NORMAL.
	FieldOptions_JsType_JsNormal = 0

	// Enum value for google.protobuf.FieldOptions.JS_STRING.
	FieldOptions_JsType_JsString = 1

	// Enum value for google.protobuf.FieldOptions.JS_NUMBER.
	FieldOptions_JsType_JsNumber = 2

	// Enum value for google.protobuf.FieldOptions.RETENTION_UNKNOWN.
	FieldOptions_OptionRetention_Unknown = 0

	// Enum value for google.protobuf.FieldOptions.RETENTION_RUNTIME.
	FieldOptions_OptionRetention_Runtime = 1

	// Enum value for google.protobuf.FieldOptions.RETENTION_SOURCE.
	FieldOptions_OptionRetention_Source = 2

	// Enum value for google.protobuf.FieldOptions.TARGET_TYPE_UNKNOWN.
	FieldOptions_OptionTargetType_Unknown = 0

	// Enum value for google.protobuf.FieldOptions.TARGET_TYPE_FILE.
	FieldOptions_OptionTargetType_File = 1

	// Enum value for google.protobuf.FieldOptions.TARGET_TYPE_EXTENSION_RANGE.
	FieldOptions_OptionTargetType_ExtensionRange = 2

	// Enum value for google.protobuf.FieldOptions.TARGET_TYPE_MESSAGE.
	FieldOptions_OptionTargetType_Message = 3

	// Enum value for google.protobuf.FieldOptions.TARGET_TYPE_FIELD.
	FieldOptions_OptionTargetType_Field = 4

	// Enum value for google.protobuf.FieldOptions.TARGET_TYPE_ONEOF.
	FieldOptions_OptionTargetType_Oneof = 5

	// Enum value for google.protobuf.FieldOptions.TARGET_TYPE_ENUM.
	FieldOptions_OptionTargetType_Enum = 6

	// Enum value for google.protobuf.FieldOptions.TARGET_TYPE_ENUM_ENTRY.
	FieldOptions_OptionTargetType_EnumEntry = 7

	// Enum value for google.protobuf.FieldOptions.TARGET_TYPE_SERVICE.
	FieldOptions_OptionTargetType_Service = 8

	// Enum value for google.protobuf.FieldOptions.TARGET_TYPE_METHOD.
	FieldOptions_OptionTargetType_Method = 9

	// Enum value for google.protobuf.MethodOptions.IDEMPOTENCY_UNKNOWN.
	MethodOptions_IdempotencyLevel_IdempotencyUnknown = 0

	// Enum value for google.protobuf.MethodOptions.NO_SIDE_EFFECTS.
	MethodOptions_IdempotencyLevel_NoSideEffects = 1

	// Enum value for google.protobuf.MethodOptions.IDEMPOTENT.
	MethodOptions_IdempotencyLevel_Idempotent = 2

	// Enum value for google.protobuf.FeatureSet.FIELD_PRESENCE_UNKNOWN.
	FeatureSet_FieldPresence_Unknown = 0

	// Enum value for google.protobuf.FeatureSet.EXPLICIT.
	FeatureSet_FieldPresence_Explicit = 1

	// Enum value for google.protobuf.FeatureSet.IMPLICIT.
	FeatureSet_FieldPresence_Implicit = 2

	// Enum value for google.protobuf.FeatureSet.LEGACY_REQUIRED.
	FeatureSet_FieldPresence_LegacyRequired = 3

	// Enum value for google.protobuf.FeatureSet.ENUM_TYPE_UNKNOWN.
	FeatureSet_EnumType_Unknown = 0

	// Enum value for google.protobuf.FeatureSet.OPEN.
	FeatureSet_EnumType_Open = 1

	// Enum value for google.protobuf.FeatureSet.CLOSED.
	FeatureSet_EnumType_Closed = 2

	// Enum value for google.protobuf.FeatureSet.REPEATED_FIELD_ENCODING_UNKNOWN.
	FeatureSet_RepeatedFieldEncoding_Unknown = 0

	// Enum value for google.protobuf.FeatureSet.PACKED.
	FeatureSet_RepeatedFieldEncoding_Packed = 1

	// Enum value for google.protobuf.FeatureSet.EXPANDED.
	FeatureSet_RepeatedFieldEncoding_Expanded = 2

	// Enum value for google.protobuf.FeatureSet.UTF8_VALIDATION_UNKNOWN.
	FeatureSet_Utf8Validation_Unknown = 0

	// Enum value for google.protobuf.FeatureSet.VERIFY.
	FeatureSet_Utf8Validation_Verify = 2

	// Enum value for google.protobuf.FeatureSet.NONE.
	FeatureSet_Utf8Validation_None = 3

	// Enum value for google.protobuf.FeatureSet.MESSAGE_ENCODING_UNKNOWN.
	FeatureSet_MessageEncoding_Unknown = 0

	// Enum value for google.protobuf.FeatureSet.LENGTH_PREFIXED.
	FeatureSet_MessageEncoding_LengthPrefixed = 1

	// Enum value for google.protobuf.FeatureSet.DELIMITED.
	FeatureSet_MessageEncoding_Delimited = 2

	// Enum value for google.protobuf.FeatureSet.JSON_FORMAT_UNKNOWN.
	FeatureSet_JsonFormat_Unknown = 0

	// Enum value for google.protobuf.FeatureSet.ALLOW.
	FeatureSet_JsonFormat_Allow = 1

	// Enum value for google.protobuf.FeatureSet.LEGACY_BEST_EFFORT.
	FeatureSet_JsonFormat_LegacyBestEffort = 2

	// Enum value for google.protobuf.FeatureSet.ENFORCE_NAMING_STYLE_UNKNOWN.
	FeatureSet_EnforceNamingStyle_Unknown = 0

	// Enum value for google.protobuf.FeatureSet.STYLE2024.
	FeatureSet_EnforceNamingStyle_2024 = 1

	// Enum value for google.protobuf.FeatureSet.STYLE_LEGACY.
	FeatureSet_EnforceNamingStyle_Legacy = 2

	// Enum value for google.protobuf.FeatureSet.VisibilityFeature.DEFAULT_SYMBOL_VISIBILITY_UNKNOWN.
	FeatureSet_DefaultSymbolVisibility_Unknown = 0

	// Enum value for google.protobuf.FeatureSet.VisibilityFeature.EXPORT_ALL.
	FeatureSet_DefaultSymbolVisibility_ExportAll = 1

	// Enum value for google.protobuf.FeatureSet.VisibilityFeature.EXPORT_TOP_LEVEL.
	FeatureSet_DefaultSymbolVisibility_ExportTopLevel = 2

	// Enum value for google.protobuf.FeatureSet.VisibilityFeature.LOCAL_ALL.
	FeatureSet_DefaultSymbolVisibility_LocalAll = 3

	// Enum value for google.protobuf.FeatureSet.VisibilityFeature.STRICT.
	FeatureSet_DefaultSymbolVisibility_Strict = 4

	// Enum value for google.protobuf.GeneratedCodeInfo.Annotation.NONE.
	GeneratedCodeInfo_Annotation_Semantic_None = 0

	// Enum value for google.protobuf.GeneratedCodeInfo.Annotation.SET.
	GeneratedCodeInfo_Annotation_Semantic_Set = 1

	// Enum value for google.protobuf.GeneratedCodeInfo.Annotation.ALIAS.
	GeneratedCodeInfo_Annotation_Semantic_Alias = 2
)
