// Copyright 2020-2025 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by github.com/bufbuild/protocompile/internal/enum enums.yaml. DO NOT EDIT.

package ast

import (
	"fmt"
	"iter"
)

// TagKind is a kind of tag. There is one value of TagKind for each
// Tag* type in this package.
type TagKind int8

const (
	TagKindInvalid TagKind = iota
	TagKindText
	TagKindExpr
	TagKindEnd
	TagKindEmit
	TagKindImport
	TagKindIf
	TagKindSwitch
	TagKindCase
	TagKindFor
	TagKindMacro
)

// String implements [fmt.Stringer].
func (v TagKind) String() string {
	if int(v) < 0 || int(v) > len(_table_TagKind_String) {
		return fmt.Sprintf("TagKind(%v)", int(v))
	}
	return _table_TagKind_String[v]
}

// GoString implements [fmt.GoStringer].
func (v TagKind) GoString() string {
	if int(v) < 0 || int(v) > len(_table_TagKind_GoString) {
		return fmt.Sprintf("ast.TagKind(%v)", int(v))
	}
	return _table_TagKind_GoString[v]
}

// ExprKind is a kind of tag. There is one value of ExprKind for each
// Expr* type in this package.
type ExprKind int8

const (
	ExprKindInvalid ExprKind = iota
	ExprKindToken
	ExprKindStruct
	ExprKindOp
)

// String implements [fmt.Stringer].
func (v ExprKind) String() string {
	if int(v) < 0 || int(v) > len(_table_ExprKind_String) {
		return fmt.Sprintf("ExprKind(%v)", int(v))
	}
	return _table_ExprKind_String[v]
}

// GoString implements [fmt.GoStringer].
func (v ExprKind) GoString() string {
	if int(v) < 0 || int(v) > len(_table_ExprKind_GoString) {
		return fmt.Sprintf("ast.ExprKind(%v)", int(v))
	}
	return _table_ExprKind_GoString[v]
}

// StructKind is a kind of expression represented by an [ExprStruct].
type StructKind int8

const (
	StructKindInvalid StructKind = iota
	StructKindGrouping
	StructKindTuple
	StructKindSlice
	StructKindMap
)

// String implements [fmt.Stringer].
func (v StructKind) String() string {
	if int(v) < 0 || int(v) > len(_table_StructKind_String) {
		return fmt.Sprintf("StructKind(%v)", int(v))
	}
	return _table_StructKind_String[v]
}

// GoString implements [fmt.GoStringer].
func (v StructKind) GoString() string {
	if int(v) < 0 || int(v) > len(_table_StructKind_GoString) {
		return fmt.Sprintf("ast.StructKind(%v)", int(v))
	}
	return _table_StructKind_GoString[v]
}

var _table_TagKind_String = [...]string{
	TagKindInvalid: "TagKindInvalid",
	TagKindText:    "TagKindText",
	TagKindExpr:    "TagKindExpr",
	TagKindEnd:     "TagKindEnd",
	TagKindEmit:    "TagKindEmit",
	TagKindImport:  "TagKindImport",
	TagKindIf:      "TagKindIf",
	TagKindSwitch:  "TagKindSwitch",
	TagKindCase:    "TagKindCase",
	TagKindFor:     "TagKindFor",
	TagKindMacro:   "TagKindMacro",
}

var _table_TagKind_GoString = [...]string{
	TagKindInvalid: "TagKindInvalid",
	TagKindText:    "TagKindText",
	TagKindExpr:    "TagKindExpr",
	TagKindEnd:     "TagKindEnd",
	TagKindEmit:    "TagKindEmit",
	TagKindImport:  "TagKindImport",
	TagKindIf:      "TagKindIf",
	TagKindSwitch:  "TagKindSwitch",
	TagKindCase:    "TagKindCase",
	TagKindFor:     "TagKindFor",
	TagKindMacro:   "TagKindMacro",
}

var _table_ExprKind_String = [...]string{
	ExprKindInvalid: "ExprKindInvalid",
	ExprKindToken:   "ExprKindToken",
	ExprKindStruct:  "ExprKindStruct",
	ExprKindOp:      "ExprKindOp",
}

var _table_ExprKind_GoString = [...]string{
	ExprKindInvalid: "ExprKindInvalid",
	ExprKindToken:   "ExprKindToken",
	ExprKindStruct:  "ExprKindStruct",
	ExprKindOp:      "ExprKindOp",
}

var _table_StructKind_String = [...]string{
	StructKindInvalid:  "StructKindInvalid",
	StructKindGrouping: "StructKindGrouping",
	StructKindTuple:    "StructKindTuple",
	StructKindSlice:    "StructKindSlice",
	StructKindMap:      "StructKindMap",
}

var _table_StructKind_GoString = [...]string{
	StructKindInvalid:  "StructKindInvalid",
	StructKindGrouping: "StructKindGrouping",
	StructKindTuple:    "StructKindTuple",
	StructKindSlice:    "StructKindSlice",
	StructKindMap:      "StructKindMap",
}
var _ iter.Seq[int] // Mark iter as used.
