name: ci
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 22 * * *'
  workflow_dispatch: {} # support manual runs
permissions:
  contents: read
jobs:
  test:
    name: test (go:${{ matrix.go-version.name }}, ${{ matrix.goarch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - name: latest
            version: 1.26.x
          - name: previous
            version: 1.25.x
        goarch: [amd64, 386]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version.version }}
      - run: make test
        env:
          GOARCH: ${{ matrix.goarch }}
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.x
      - run: make benchmarks
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.x
      - run: make generate
      - run: make checkgenerate
      - run: make lint
