name: ci
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 22 * * *'
  workflow_dispatch: {} # support manual runs
permissions:
  contents: read
jobs:
  test:
    name: test (go:${{ matrix.go-version.name }}, ${{ matrix.goarch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - name: latest
            version: 1.26.x
          - name: previous
            version: 1.25.x
        goarch: [amd64, 386]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version.version }}
      - name: Test
        run: make test
        env:
          GOARCH: ${{ matrix.goarch }}
  benchmarks:
    name: benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26.x
      - name: Benchmarks
        run: make benchmarks
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26.x
      # Lint & gofmt guidelines depend on the Go version. Only check generated
      # code and lint on the most recent supported version.
      - name: Generate
        run: make generate
      - name: Check generate
        run: make checkgenerate
      - name: Lint
        run: make lint
